server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://msvc-usuarios:8080 # Cambiado a nombre del Service y puerto definido en Kubernetes
            predicates:
              - Path=/users/**
          - id: auth-service
            uri: http://msvc-auth:8081 # Cambiado a nombre del Service y puerto definido en Kubernetes
            predicates:
              - Path=/rest/auth/**
          - id: portfolio-service
            uri: http://msvc-portafolios:8083 # Cambiado a nombre del Service y puerto definido en Kubernetes
            predicates:
              - Path=/portfolios/**
          - id: asset-service
            uri: http://msvc-activos:8084 # Cambiado a nombre del Service y puerto definido en Kubernetes
            predicates:
              - Path=/assets/**
          - id: assetportfolio-service
            uri: http://msvc-activosportafolios:8085 # Cambiado a nombre del Service y puerto definido en Kubernetes
            predicates:
              - Path=/assetsportfolios/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
