server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://msvc-usuarios:9001
            predicates:
              - Path=/users/**
          - id: auth-service
            uri: http://msvc-auth:9000
            predicates:
              - Path=/rest/auth/**
          - id: asset-service
            uri: http://localhost:9003
            predicates:
              - Path=/assets/**
          - id: portfolio-service
            uri: http://localhost:9002
            predicates:
              - Path=/portfolios/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
