server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://msvc-usuarios:8080
            predicates:
              - Path=/users/**
          - id: auth-service
            uri: http://msvc-auth:8081
            predicates:
              - Path=/rest/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
