apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: msvc-auth
  name: msvc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: msvc-auth
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: msvc-auth
    spec:
      containers:
        - env:
            - name: FEIGN_CLIENT_URL
              value: http://msvc-usuarios:8080
          image: gcr.io/infra-odyssey-437506-a3/assetmaker:auth-amd-1.0.2
          name: msvc-auth
          ports:
            - containerPort: 9000
              protocol: TCP
      restartPolicy: Always
