apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: msvc-auth
  name: msvc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: msvc-auth
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: msvc-auth
    spec:
      containers:
        - env:
            - name: FEIGN_CLIENT_URL
              value: http://msvc-usuarios:9001
          image: juanhoyos/assetmaker:auth-1.0.0
          name: msvc-auth
          ports:
            - containerPort: 9000
              protocol: TCP
      restartPolicy: Always
