apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: msvc-gateway
  name: msvc-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: msvc-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: msvc-gateway
    spec:
      containers:
        - image: gcr.io/infra-odyssey-437506-a3/assetmaker/gateway-amd-1.0.3
          name: msvc-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
