apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f .\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: msvc-usuarios
  name: msvc-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: msvc-usuarios
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f .\docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: msvc-usuarios
    spec:
      containers:
        - image: gcr.io/infra-odyssey-437506-a3/assetmaker:users-1.0.0
          name: msvc-usuarios
          ports:
            - containerPort: 9001
              protocol: TCP
      restartPolicy: Always
