apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: msvc-gateway
  name: msvc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: msvc-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: msvc-gateway
    spec:
      containers:
        - image: juanhoyos/assetmaker:gateway-1.0.0
          name: msvc-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
