apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f .\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: msvc-portafolios
  name: msvc-portafolios
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: msvc-portafolios
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f .\docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: msvc-portafolios
    spec:
      containers:
        - env:
            - name: FEIGN_CLIENT_URL
              value: http://msvc-usuarios:8080
          image: gcr.io/infra-odyssey-437506-a3/assetmaker:portafolios-1.0.3
          name: msvc-portafolios
          ports:
            - containerPort: 9002
              protocol: TCP
      restartPolicy: Always