apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: msvc-activosportafolios
  name: msvc-activosportafolios
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: msvc-activosportafolios
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: msvc-activosportafolios
    spec:
      containers:
        - env:
            - name: FEIGN_CLIENT_URL
              value: http://msvc-portafolios:8083
            - name: FEIGN_CLIENT_URL_ASSETS
              value: http://msvc-activos:8084
          image: gcr.io/infra-odyssey-437506-a3/assetmaker/juanhoyos/assetmaker:activosportafolios-1.0.0
          name: msvc-activosportafolios
          ports:
            - containerPort: 9004
              protocol: TCP
      restartPolicy: Always
