CREATE TYPE RISK_PROFILE AS ENUM('Conservative', 'Moderate', 'Risky');
CREATE CAST (varchar AS risk_profile) WITH INOUT AS IMPLICIT;

CREATE TABLE "user" (
	ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(32) NOT NULL,
	LAST_NAMES VARCHAR(64) NOT NULL,
	EMAIL VARCHAR(128) UNIQUE NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL,
	RISK_PROFILE RISK_PROFILE NOT NULL
);

CREATE TABLE PORTFOLIO (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(32),
	DESCRIPTION VARCHAR(128),
	AVERAGE_ANNUAL_RETURN INTEGER,
	BEST_12MONTH_RETURN INTEGER,
	WORST_12MONTH_RETURN INTEGER,
	BEST_20MONTH_RETURN INTEGER,
	WORST_20MONTH_RETURN INTEGER,
	ID_USER INTEGER,
	FOREIGN KEY(ID_USER) REFERENCES "user" (ID)
);

CREATE TABLE ASSET (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(32),
	DESCRIPTION VARCHAR(128),
	ASSET_TYPE VARCHAR(128)
);

CREATE TABLE CONTAINS (
	ID SERIAL PRIMARY KEY,
	ID_PORTFOLIO INTEGER,
	ID_ASSET INTEGER,
	FOREIGN KEY (ID_PORTFOLIO) REFERENCES PORTFOLIO(ID),
	FOREIGN KEY (ID_ASSET) REFERENCES ASSET(ID)
);