CREATE TYPE RISK_PROFILE AS ENUM('Conservative', 'Moderate', 'Risky');
CREATE CAST (varchar AS risk_profile) WITH INOUT AS IMPLICIT;

CREATE TABLE "user" (
	ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(32) NOT NULL,
	LAST_NAMES VARCHAR(64) NOT NULL,
	EMAIL VARCHAR(128) UNIQUE NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL,
	RISK_PROFILE RISK_PROFILE NOT NULL
);

CREATE TABLE PORTFOLIO (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(32),
	DESCRIPTION VARCHAR(128),
	AVERAGE_ANNUAL_RETURN NUMERIC(5,2),
	PORTFOLIO_PERFORMANCE NUMERIC(5,2),
	STANDARD_DEVIATION NUMERIC(5,2),
	ID_USER INTEGER,
	FOREIGN KEY(ID_USER) REFERENCES "user" (ID)
);

CREATE TABLE ASSET (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(32),
	SYMBOL VARCHAR(4),
	FIVE_YEAR_PERFORMANCE NUMERIC(5,2),
	FIVE_YEAR_RISK NUMERIC(5,2),
	MAXIMUM_YIELD NUMERIC(5,2),
	MINIMUM_YIELD NUMERIC(5,2)
);

CREATE TABLE CONTAINS (
	ID SERIAL PRIMARY KEY,
	ID_PORTFOLIO INTEGER,
	ID_ASSET INTEGER,
	FOREIGN KEY (ID_PORTFOLIO) REFERENCES PORTFOLIO(ID),
	FOREIGN KEY (ID_ASSET) REFERENCES ASSET(ID)
);